server:
  port: ${MARKET_SERVICE_PORT:8082}
  shutdown: graceful

spring:
  datasource:
    url: ${MARKET_DB_URL:jdbc:postgresql://postgres:5432/${POSTGRES_DB:tradeapp}}
    username: ${MARKET_DB_USERNAME:${POSTGRES_USER}}
    password: ${MARKET_DB_PASSWORD:${POSTGRES_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

tradeapp:
  market:
    topic: ${tradeapp_PRICE_TOPIC:tradeapp.market.prices}
    history:
      years: ${tradeapp_MARKET_HISTORY_YEARS:10}
      interval: ${tradeapp_MARKET_HISTORY_INTERVAL:SECONDS}
      generation-delay-ms: ${tradeapp_MARKET_GENERATION_DELAY_MS:1000}

springdoc:
  swagger-ui:
    enabled: false
